version: '3'

tasks:
  kind:infra-up:
    desc: Create kind cluster and install Istio
    cmds:
      - kind create cluster --name gitops-cluster
      - istioctl install --set profile=minimal --set meshConfig.accessLogFile=/dev/stdout

  kind:infra-down:
    desc: Tear down kind cluster
    cmds:
      - kind delete cluster --name gitops-cluster

  install-flux:
    vars:
      CLUSTER: kind
    desc: Install and configure Flux
    cmds:
      - |
        flux bootstrap git \
          --url=ssh://git@github.com/vedantthapa/devsecops-platform \
          --branch=main \
          --path=kubernetes/clusters/{{.CLUSTER}} \
          --components-extra="image-reflector-controller,image-automation-controller"
