apiVersion: v1
kind: Namespace
metadata:
  name: capacitor
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: capacitor
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    digest: 'sha256:1e72940be8383cd5054e3efcff8ec36f27e33959a4b940fc4b956c932083578b'
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: 'https://token.actions.githubusercontent.com'
        subject: '^https://github.com/gimlet-io/capacitor.*$'
