apiVersion: v1
kind: Namespace
metadata:
  name: capacitor
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
  namespace: capacitor
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: '0.4.1'
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: 'https://token.actions.githubusercontent.com'
        subject: '^https://github.com/gimlet-io/capacitor.*$'
