---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/components/controllers
  prune: true
  wait: true
  patches:
    # patch istio-ingress namespace with injection label
    - patch: |-
        - op: add
          path: /metadata/labels
          value:
            istio-injection: enabled
      target:
        kind: Namespace
        name: istio-ingress
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/components/configs
  prune: true
  patches:
    # configure ClusterIssuer as selfSigned issuer
    - patch: |-
        - op: add
          path: /spec
          value:
            selfSigned: {}
      target:
        kind: ClusterIssuer
        name: issuer
    # add DNS name
    - patch: |-
        - op: add
          path: /spec/dnsNames
          value: 
            - apps.example.com
      target:
        kind: Certificate
        name: mesh-gateway-cert

