apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/controllers/
patches:
    # patch istio-ingress namespace with injection label
    - patch: |-
        - op: add
          path: /metadata/labels
          value:
            istio-injection: enabled
      target:
        kind: Namespace
        name: istio-ingress
