apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nginx/
  - vs.yaml
  - allow-ingress-to-nginx.yaml

namespace: nginx

patches:
  - path: ./deployment-patch.yaml
    target:
      kind: Deployment
      name: nginx
