apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    service: nginx
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: cgr.dev/chainguard/nginx:latest@sha256:85d57269d186fdb0ed741ff8cd27a669d4fdcecbbf155293c1d7ecb55b0039a4
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 400Mi
        securityContext:
          allowPrivilegeEscalation: false
